---
title: "Reproducible Research quiz1"
output: html_document
---
#### Problem 1.
**Q:** Suppose I conduct a study and publish my findings. Which of the following is an example of a replication of my study?  
**A:** An investigator at another institution conducts a study addressing the *same question*, collects her own data, analyzes it separately from me, and publishes her own findings.

#### Problem 2.
**Q:** Which of the following is a requirement for a published data analysis to be reproducible?  
**A:** The full computer code for doing the data analysis is made publicly available.

#### Problem 3.
**Q:** Which of the following is an example of a reproducible study?  
**A:** The study's analytic data and computer code for the data analysis are publicly available. When the code is run on the analytic data, the findings are identical to the published results.  

#### Problem 4.
**Q:** Which of the following is a reason that a study might NOT be fully replicated?  
**A:** The original study was very expensive and there is no money to repeat it in a different setting.  

#### Problem 5.
**Q:** Which of the following is a reason why publishing reproducible research is increasingly important?  
**A:** New technologies are increasing the rate of data collection, creating datasets that are more complex and extremely high dimensional.  

#### Problem 6.
**Q:** What is the role of processing code in the research pipeline?  
**A:** It transforms the measured data into analytic data.  

#### Problem 7.
**Q:** Which is a goal of literate statistical programming?  
**A:** Combine explanatory text and data analysis code in a single document.  

#### Problem 8.
**Q:** What does it mean to weave a literate statistical program?  
**A:** Transform the literate program into a *human readable* document.  

#### Problem 9.
**Q:** Which of the following is required to implement a literate programming system?  
**A:** A documentation language like LaTeX.  

#### Problem 10.
**Q:** What is one way in which the knitr system differs from Sweave?  
**A:** knitr allows for the use of markdown instead of LaTeX.  
